### ISSUE TITLE
How can I serialize JSON into hex?

### ISSUE THREAD

**Issue by 0xWWLG** [memtrip/eos-swift#3]
How can I serialize JSON(Any type) into hex?
eg:
input:
{
    "from":"testtest123",
    "to":"receiver456",
    "quantity":"0.0001 EOS",
    "memo":"meet-dev-tools works!"
}

output:
3044a852df3c1b7d00000000000e1660010000000000000004454f5300000000156d6565742d6465762d746f6f6c7320776f726b7321

I know the official interface "/v1/chain/abi_json_to_bin" can be done, but how to use Swift? I hope to get your help. Thank you very much.

**Comment by samkirton** [comment]
Is there a reason why you would like to use JSON? If you review the unit tests, they use model objects that implement `Encodable` to serialise data into hex. Your example would look like:
```swift
public struct TransferArgs : Encodable {
    let from: AccountNameWriterValue
    let to: AccountNameWriterValue
    let quantity: AssetWriterValue
    let memo: String
}

let args = TransferArgs(
    from: AccountNameWriterValue(name: "memtripblock"),
    to: AccountNameWriterValue(name: "memtripproxy"),
    quantity: AssetWriterValue(asset: "0.0001 EOS"),
    memo: "memo"
)

let hexValue = args.toHex(AbiEncoder(capacity: 512))
```

The library also includes an abstraction layer for system contract actions, such as transfer, you can find examples in these integration tests:
https://github.com/memtrip/eos-swift/tree/master/eosswiftTests/eos-chain-actions/transaction

**Comment by samkirton** [comment]
Join us on telegram if you need more help, github isn't checked as often: http://t.me/joinchat/JcIXl0x7wC9cRI5uF_EiQA
